AllCops:
  NewCops: disable
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    -  vendor/bundle/**/*
    -  vendor/**/*.rb
  SuggestExtensions: false

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*'
    - 'lib/error/*'

Style/Documentation:
  Enabled: true

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 30

Style/FrozenStringLiteralComment:
  Enabled: false

